#ifndef MUN_ABI_H_
#define MUN_ABI_H_

#include <stdint.h>

/**
 * Represents a globally unique identifier (GUID).
 *
 * GUIDs are generated by taking the MD5 hash of a type's name.
 *
 * <div rustbindgen derive="Clone" derive="Copy" derive="Debug" derive="Eq" derive="PartialEq" derive="Ord" derive="PartialOrd"></div>
 */
typedef struct
{
    /// 16-byte MD5 hash
    const uint8_t b[16];
} MunGuid;

/**
 * Represents a group of types that illicit the same characteristics.
 *
 * <div rustbindgen hide></div>
 */
typedef enum
{
    /// A fundamental type (i.e. `()`, `bool`, `float`, `int`, etc.)
    MunFundamentalTypes = 0,
    /// A struct type (i.e. record, tuple, or unit structs)
    MunStructTypes = 1
} MunTypeGroup;

/**
 * <div rustbindgen hide></div>
 */
typedef uint8_t MunTypeGroup_t;

/**
 * Represents the type declaration for a value type.
 *
 * TODO: add support for structs, polymorphism, enumerations, type parameters, generic type definitions, and constructed generic types.
 *
 * <div rustbindgen derive="Debug"></div>
 */
typedef struct
{
    /// Type GUID
    const MunGuid guid;
    /// Type name
    const char *name;
    /// The exact size of the type in bits without any padding
    uint64_t size_in_bits;
    /// The alignment of the type
    uint32_t alignment;
    /// Type group
    const MunTypeGroup_t group;
} MunTypeInfo;

/**
 * Represents the kind of memory management a struct uses.
 *
 * <div rustbindgen hide></div>
 */
typedef enum
{
    /// A garbage collected struct is allocated on the heap and uses reference semantics when passed
    /// around.
    MunStructMemoryKindGC,

    /// A value struct is allocated on the stack and uses value semantics when passed around.
    ///
    /// NOTE: When a value struct is used in an external API, a wrapper is created that _pins_ the
    /// value on the heap. The heap-allocated value needs to be *manually deallocated*!
    MunStructMemoryKindValue,
} MunStructMemoryKind;

/**
 * <div rustbindgen hide></div>
 */
typedef uint8_t MunStructMemoryKind_t;

/**
 * Represents the accessibility level of a function, module, or type.
 *
 * <div rustbindgen hide></div>
 */
typedef enum
{
    /// Publicly (and privately) accessible
    MunPrivacyPublic = 0,
    /// Privately accessible
    MunPrivacyPrivate = 1
} MunPrivacy;

/**
 * <div rustbindgen hide></div>
 */
typedef uint8_t MunPrivacy_t;

/**
 * Represents a function signature.
 *
 * <div rustbindgen derive="Clone" derive="Debug"></div>
 */
typedef struct
{
    /// Function name
    const char *name;
    /// Argument types
    const MunTypeInfo *const *arg_types;
    /// Optional return type
    const MunTypeInfo *return_type;
    /// Number of argument types
    const uint16_t num_arg_types;
    /// Function accessibility level
    const MunPrivacy_t privacy;
} MunFunctionSignature;

/**
 * Represents a function declaration.
 *
 * `fn_ptr` can be used to call the declared function.
 *
 * <div rustbindgen derive="Clone" derive="Debug"></div>
 */
typedef struct
{
    /// Function signature
    const MunFunctionSignature signature;
    /// Function pointer
    const void *fn_ptr;
} MunFunctionInfo;

/**
 * Represents a struct declaration.
 *
 * <div rustbindgen derive="Clone" derive="Debug"></div>
 */
typedef struct
{
    /// Struct name
    const char *name;
    /// Struct fields' names
    const char *const *field_names;
    /// Struct fields' information
    const MunTypeInfo *const *field_types;
    /// Struct fields' offsets
    const uint16_t *field_offsets;
    // TODO: Field accessibility levels
    // const MunPrivacy_t *field_privacies;
    /// Number of fields
    const uint16_t num_fields;
    // TODO: Add struct accessibility level
    /// Struct memory kind
    const MunStructMemoryKind_t memory_kind;
} MunStructInfo;

/**
 * Represents a module declaration.
 *
 * <div rustbindgen derive="Debug"></div>
 */
typedef struct
{
    /// Module path
    const char *path;
    /// Module functions
    const MunFunctionInfo *functions;
    /// Number of module functions
    const uint32_t num_functions;
    /// Module types
    const MunTypeInfo *const *types;
    /// Number of module types
    const uint32_t num_types;
} MunModuleInfo;

/**
 * Represents a function dispatch table. This is used for runtime linking.
 *
 * Function signatures and pointers are stored separately for cache efficiency.
 *
 * <div rustbindgen derive="Debug"></div>
 */
typedef struct
{
    /// Function signatures
    const MunFunctionSignature *signatures;
    /// Function pointers
    const void **fn_ptrs;
    /// Number of functions
    const uint32_t num_entries;
} MunDispatchTable;

/**
 * Represents an assembly declaration.
 * 
 * <div rustbindgen derive="Debug"></div>
 */
typedef struct
{
    /// Symbols of the top-level module
    const MunModuleInfo symbols;
    /// Dispatch table
    MunDispatchTable dispatch_table;
    /// Paths to assembly dependencies
    const char *const *dependencies;
    /// Number of dependencies
    const uint32_t num_dependencies;
} MunAssemblyInfo;

#endif
